"""empty message

Revision ID: 2d5fb6241cd3
Revises: 640f57062887
Create Date: 2017-11-01 18:45:28.892522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d5fb6241cd3'
down_revision = '640f57062887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_history_userId'), 'history', ['userId'], unique=False)
    op.drop_index('ix_history_userId', table_name='history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_history_userId', 'history', ['userId'], unique=False)
    op.drop_index(op.f('ix_history_userId'), table_name='history')
    # ### end Alembic commands ###
