"""empty message

Revision ID: 640f57062887
Revises: 
Create Date: 2017-10-30 19:42:51.763698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640f57062887'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('state', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_history_id'), 'history', ['id'], unique=False)
    op.create_index(op.f('ix_history_state'), 'history', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_state'), table_name='history')
    op.drop_index(op.f('ix_history_id'), table_name='history')
    op.drop_column('history', 'state')
    # ### end Alembic commands ###
